### ISSUE TITLE
WindowStyle.None error dialog on Export Extensions... action.  (v0.6.72)

### ISSUE THREAD

**Issue by HakanCelikMKA** [loop8ack/ExtensionPackTools#42]
Hello,

I've just updated the extension to the latest version  (v0.6.72) through Visual Studio Extension Manager. 
It was working without a problem before, but now when I use the following menu option
Extensions > Import and Export Extensions > Export Extensions...
I get and error window with the following content :

Microsoft Visual Studio
Extension Manager 2019

WindowStyle.None is the only valid value for WindowStyle when AllowsTransparency is true.

![image](https://user-images.githubusercontent.com/30536523/104457653-62d05d80-55bb-11eb-83f9-1b864c7fca74.png)

Could this be related to the latest commit : #41 ?

Thanks.

My environment is as follows :
Microsoft Windows 10 Enterprise Version	10.0.18363 Build 18363
Microsoft Visual Studio Professional 2019 Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework Version 4.8.03752

**Comment by bdancer** [comment]
Same happens for me with the latest update of the version for 2017.

**Comment by TheJoelGray** [comment]
Same on VS 2019 Community.

**Comment by TheJoelGray** [comment]
FYI I just discovered that there is a closed issue #41 that addresses this. You can download the nightly and that seems to resolve the issue.
[VS2017 version](https://www.vsixgallery.com/extension/e83d71b8-8bfc-4e06-b145-b0388910c016/)
[VS2019 version](https://www.vsixgallery.com/extension/4a196712-2c3f-4730-ad1d-e7cda4185eb2/)

**Comment by GrumpyMeow** [comment]
Same here on VS 2019 Professional. I'll try the nightly version.

**Comment by jvsca** [comment]
Version v0.6.74 (nightly) seems to work (tried Export only).

1. In Dark Theme the text is Black.
2. The Export button shows as: &Export:
![image](https://user-images.githubusercontent.com/2821731/104603422-62cb6e80-564a-11eb-84d1-5e7a852879df.png)
3. The Import button shows as: &Import:
![image](https://user-images.githubusercontent.com/2821731/104603485-78d92f00-564a-11eb-85a0-f76bcb196ed1.png)

**Comment by HakanCelikMKA** [comment]
@jvsca, I can also confirm Extension Manager 2019 nightly (v0.6.74) export functionality is working on my installation (Microsoft Visual Studio Professional 2019 Version 16.8.3) exactly as it does on yours (screen shots as well).  I don't have the time to check import functionality now, due to time constraints, sorry.
Thanks to @TheJoelGray for pointing out the option of using the nightly and providing the links.

**Comment by jakeafoster** [comment]
@jvsca The justification for using "&Export" was explained in #37 by @astrohart. I have coped and pasted the explanation below:
![image](https://user-images.githubusercontent.com/46297995/104683618-672b8080-574b-11eb-9429-9609c36137e5.png)

**Comment by jakeafoster** [comment]
I am running Visual Studio Community 2019 v16.8.4 with Extension Manager 2019 nightly v0.6.74.

Export functionality works for me.

Import functionality appeared to be working but did not actually install any of the extensions. I tried importing again and the following message appeared:
![image](https://user-images.githubusercontent.com/46297995/104686479-685fac00-5751-11eb-977d-0f1c0b39bc82.png)

The select Select/deselect all button does not work on the Import window either.

Does this happen to anyone else?

**Comment by astrohart** [comment]
@madskristensen I will be happy to work on this.

**Comment by astrohart** [comment]
@madskristensen In my mind, there are three issues at work here:

- `WindowStyle.None` error needs to be fixed
- Dialog text not showing up in Dark Theme
- No extensions imported

Respectfully request permission to reference three individual issues off this thread, so that PRs may be submitted, one per each issue.

Furthermore, I also strongly recommend adding logging.  Respectfully request permission to add logging support.  The suggestion would be to refactor the code to rely on IoC and use a `Castle.Windsor` interceptor to handle the logging -- or some other AOP approach (where feasible).  I have my own logging library code that relies on `log4net` I can stitch into the project.  Is it OK to use `log4net`? My though is basically to have the extension write a `ExtensionPackTools.log` file to the user's TEMP folder, and begin a new log file (named after the current date/time in UTC) upon each start of Visual Studio/load of the extension by the IDE.  This way when the community has issues the logs can be sent up/attached to the issue.

**Comment by jakeafoster** [comment]
@astrohart The WindowStyle.None error was fixed in #41 but this update is only available on the nightly version at the moment.

**Comment by jvsca** [comment]
@JkeFos The character to indicate accelerator keys in WPF is "_" (in WinForms is "&").
The extension's dialogs are WPF, then the code should use "_Export" instead of "&Export".

@madskristensen 
Line #24 in ImportWindow.xaml.cs should be changed from:
`btnOk.Content = purpose == Purpose.InstallForSolution ? "&Install" : purpose == Purpose.Import ? "&Import" : "&Export";`
to:
`btnOk.Content = purpose == Purpose.InstallForSolution ? "_Install" : purpose == Purpose.Import ? "_Import" : "_Export";`

**Comment by astrohart** [comment]
I think it's great that this issue has been filed and I want to say thank you for those who raised this issue.

However, it seems like, reading the comments, that this issue should be split into 2-3 separate GitHub issues.  For the ease of tracking pull-requests and merges.  Can we do this?

**Comment by astrohart** [comment]
> @madskristensen
> Line number 24 in ImportWindow.xaml.cs should be changed from:
> `btnOk.Content = purpose == Purpose.InstallForSolution ? "&Install" : purpose == Purpose.Import ? "&Import" : "&Export";`
> to:
> `btnOk.Content = purpose == Purpose.InstallForSolution ? "_Install" : purpose == Purpose.Import ? "_Import" : "_Export";`

@JkeFos  @jvsca This change has been made by me and is pending a pull request.  I'm finding it difficult to file a pull request to correspond to this issue because there are really 2-3 separate problems mentioned in this discussion and I am trying to figure out how to associate my pull-request fixes appropriately to this issue-of-issues.
