### ISSUE TITLE
Error when trying to Export extensions in vs 2022 preview

### ISSUE THREAD

**Issue by ekrogh** [loop8ack/ExtensionPackTools#70]
**Describe the bug**
When I try to Export or Import extensions in Visual Studio Community 2022 (64-bit) - Preview, Version 17.6.0 Preview 2.0 , Extension Manager 2022 Version: 1.1.82, then I get this error message:
"
Extension Manager 2022
Could not load type
'Microsoft.VisualStudio.ExtensionManager.GalleryOnlineExtensio n' from assembly 'Microsoft.VisualStudio.ExtensionEngine,
Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
"

**To Reproduce**
1. Open VS 2022 Preview  Version 17.6.0 Preview 2.0
2. Select Extensions --> Import and Export Extensions --> Export Extensions or Import Extensions
3. Error message pops up.

**Expected behavior**
Get window where to select extensions to export/import

**Screenshots**
![image](https://user-images.githubusercontent.com/5005577/225164677-53dfd34f-398a-438b-9a1f-7c6ee1ff5f62.png)

--
Eigil

**Comment by robert-andrzejuk** [comment]
@madskristensen  Any ideas for a workaround?

**Comment by DonovanAGBR** [comment]
Two different ways to get to the same error. Behind the scenes, it's _probably_ the exact same problem.

**Comment by NotAClue** [comment]
It's still an issue any ideas?

**Comment by loop8ack** [comment]
This project seems to be no longer maintained.
The error comes because since some Visual Studio update the internal dependencies have been changed.

Fix in code:

Go to the following folder:
%ProgramFiles%\Microsoft Visual Studio\2022\Preview\Common7\IDE\PrivateAssemblies
(I've testet with version 17.6 Preview 7)

There you need to copy the following files...
* Microsoft.VisualStudio.ExtensionEngine.dll
* Microsoft.VisualStudio.ExtensionEngineContract.dll
* Microsoft.VisualStudio.ExtensionManager.dll
* Microsoft.VisualStudio.ExtensionsExplorer.dll

... and put them in the project under "\lib\2022".

Add the new Microsoft.VisualStudio.ExtensionEngineContract.dll to the project as a reference. To do this, simply copy the following lines and paste them into the csproj file with the other matching references (line 75 - 86).

```xml
<Reference Include="Microsoft.VisualStudio.ExtensionEngineContract">
  <HintPath>..\..\lib\2022\Microsoft.VisualStudio.ExtensionEngineContract.dll</HintPath>
  <Private>False</Private>
</Reference>
```

After that in the ExtensionManager2022 project you have to derive the class "GalleryEntry" from "OnlineExtensionBase" - just let Visual Studio implement all missing properties as Auto-Property.

Then in my test everything worked again, but keep in mind that I only did a smoke test.
Also, I don't know what update broke the project, maybe someone else has more information on this?

You can find a compiled version here: [AppVeyor ExtensionPackTools Artifacts](https://ci.appveyor.com/project/madskristensen/extensionpacktools/builds/47040465/artifacts)
But keep in mind that this is not an official version.

**Comment by loop8ack** [comment]
#71 is a duplicate of #70, this should also be closed.

And are you still actively developing this project?

If not, would it be ok if I took it over?
I have a few ideas for features and how I would build the project, but they would go far beyond a pull request.

**Comment by zackmuc** [comment]
Microsoft.VisualStudio.ExtensionEngineContract.dll does not exit in my VS 17.5.5

**Comment by robert-andrzejuk** [comment]
@loop8ack I'm still having issues:
![image](https://github.com/madskristensen/ExtensionPackTools/assets/17534969/ce8f9806-fc25-4446-8c23-935763bd675e)

**Comment by loop8ack** [comment]
@robert-andrzejuk At which function and which Visual Studio version do you use?

**Comment by robert-andrzejuk** [comment]
Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.7.0 Preview 1.0
"Import Extensions..."

**Comment by loop8ack** [comment]
I've created a pull request.

The build results:
https://ci.appveyor.com/project/madskristensen/extensionpacktools/builds/47089900/artifacts

**Comment by loop8ack** [comment]
@robert-andrzejuk
I found a solution to the problem that the two versions (Normal and Preview) differ too much.
I took the repository from @madskristensen, I couldn't set up AppVeyor yet, so I attached a build for you.
Please test if it solves your problem, then I'll put an update online.

[Download: ExtensionManager2022.zip](https://github.com/loop8ack/ExtensionPackTools/files/11520153/ExtensionManager2022.zip)

Edit:
AppVeyor is live: https://ci.appveyor.com/project/loop8ack/extensionpacktools
An update for the Visual Studio Marketplace is also coming.
