### ISSUE TITLE
Error importing extensions in VS 2022 17.9.2

### ISSUE THREAD

**Issue by FIASJason** [loop8ack/ExtensionPackTools#81]
I'm setting up a new machine and downloaded the most recent build of Visual Studio 2022 (17.9.2) and Extension Manager 2022 (1.2.160).

When I attempt to import or export my extensions, I get the following error:

    Extension Manager 2022
    Method 'get_IsPublisherDomainverified' in type
    'ExtensionManager.V17_7.GalleryEntry' from assembly
    'ExtensionManager2022.V17_7, Version—I-O.O.O.
    Culture:neutral, PublicKeyToken=null' does not have an
    implementation.

![image](https://github.com/loop8ack/ExtensionPackTools/assets/145747752/0682a2d4-5773-4e3e-a7df-1ce002ab53d5)

This seems to be the same issue as #80.

**Comment by loop8ack** [comment]
You're absolutely right, these two issues are indeed related.
This extension relies on DLLs from Visual Studio, which can be subject to changes during Visual Studio development, leading to such errors. In this case, an abstract IsPublisherDomainVerified property has been added.

Unfortunately, I haven't found a robust long-term solution for this issue yet. Do you have any ideas? The only approach that comes to mind is to search for the DLLs on the first launch and generate the required code ourselves, but this could introduce complexity and other potential errors.

I've updated the DLLs, resolved the conflicts, and published an update (Version 1.2.182).
Please test to see if the issue is resolved on your end.

**Comment by FIASJason** [comment]
Thanks, everything seems to be working now.
